let token='', rules=[], lastPlan=null;
const expanded=new Set();
const $=id=>document.getElementById(id);
async function api(path, options={}){options.headers={...(options.headers||{}),'X-FolderMirror-Token':token};const r=await fetch(path,options);if(path==='/api/status')token=r.headers.get('X-FolderMirror-Token')||token;if(!r.ok)throw new Error(await r.text());return r.json()}
function effective(path){let value=false,best=-1;for(const r of rules){if(r.path===''||path===r.path||path.startsWith(r.path+'/')){const d=r.path===''?0:r.path.split('/').length;if(d>=best){best=d;value=r.include}}}return value}
function explicit(path){return rules.find(r=>r.path===path)}
function setRule(path,value){const inherited=effective(path.includes('/')?path.slice(0,path.lastIndexOf('/')):'');rules=rules.filter(r=>r.path!==path);if(value!==inherited||path==='')rules.push({path,include:value});rules.sort((a,b)=>a.path.localeCompare(b.path));$('selected').textContent=rules.length;lastPlan=null;$('apply').disabled=true}
function nodeView(n){const hasChildren=Boolean(n.children?.length),isOpen=expanded.has(n.path);const toggle=document.createElement('button');toggle.className='fold';toggle.type='button';toggle.disabled=!hasChildren;toggle.setAttribute('aria-label',`${isOpen?'Collapse':'Expand'} ${n.name}`);toggle.setAttribute('aria-expanded',String(isOpen));toggle.textContent=hasChildren?'›':'';toggle.onclick=()=>{if(isOpen)expanded.delete(n.path);else expanded.add(n.path);renderTree(window.treeData)};const box=document.createElement('input');box.type='checkbox';box.checked=effective(n.path);box.setAttribute('aria-label',`Mirror ${n.name}`);box.onchange=()=>{setRule(n.path,box.checked);renderTree(window.treeData)};const row=document.createElement('div');row.className='node-row';const label=document.createElement('label');label.textContent=n.name;label.onclick=()=>{if(hasChildren)toggle.click()};row.append(toggle,box,label);if(explicit(n.path)){const badge=document.createElement('span');badge.className='override';badge.textContent='override';row.append(badge)}const wrap=document.createElement('div');wrap.append(row);if(hasChildren&&isOpen){const children=document.createElement('div');children.className='children';for(const c of n.children)children.append(nodeView(c));wrap.append(children)}return wrap}
function renderTree(tree){const host=$('tree'),nodes=tree.children||[];host.replaceChildren(...nodes.map(nodeView));if(!nodes.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='The source folder has no subfolders.';host.append(empty)}}
function renderPlan(p){p={create:p.create||[],remove:p.remove||[],skip:p.skip||[]};lastPlan=p;const host=$('plan');host.replaceChildren();for(const [key,title] of [['create','Create links'],['remove','Remove stale links'],['skip','Needs attention']]){if(!p[key].length)continue;const h=document.createElement('h3');h.textContent=`${title} · ${p[key].length}`;host.append(h);for(const a of p[key]){const d=document.createElement('div');d.className=`item ${key}`;d.textContent=`${a.path}${a.detail?' — '+a.detail:''}`;host.append(d)}}const changes=p.create.length+p.remove.length;$('apply').disabled=changes===0;$('message').textContent=changes?`${changes} safe change${changes===1?'':'s'} ready to apply.`:'Mirror is up to date.'}
async function init(){try{const s=await api('/api/status');$('source').textContent=s.source;$('target').textContent=s.target;$('platform').textContent=`${s.platform} · ${s.instance}`;$('managed').textContent=s.managedFiles;rules=s.rules||[];$('selected').textContent=rules.length;window.treeData=await api('/api/tree');renderTree(window.treeData)}catch(e){$('message').textContent=e.message;$('message').className='message error'}}
$('save').onclick=async()=>{try{await api('/api/rules',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(rules)});$('message').textContent='Choices saved. Preview the resulting changes.'}catch(e){$('message').textContent=e.message;$('message').className='message error'}};
$('preview').onclick=async()=>{try{await api('/api/rules',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(rules)});renderPlan(await api('/api/plan',{method:'POST'}))}catch(e){$('message').textContent=e.message;$('message').className='message error'}};
$('apply').onclick=async()=>{if(!lastPlan)return;try{renderPlan(await api('/api/apply',{method:'POST'}));const s=await api('/api/status');$('managed').textContent=s.managedFiles;$('apply').disabled=true;$('message').textContent='Reconciliation complete.'}catch(e){$('message').textContent=e.message;$('message').className='message error'}};
init();
